// @flow

const ACTION_TYPES = {
    ADD_PERSON: 'ADD_PERSON',
    CHANGE_DROPDOWN: 'CHANGE_DROPDOWN',
    CHANGE_FILTER: 'CHANGE_FILTER',
    TOGGLE_PARENTS: 'TOGGLE_PARENTS'
}

export default ACTION_TYPES;
