// @flow

const ACTION_TYPES = {
    ADD_PERSON: 'ADD_PERSON',
    CHANGE_DROPDOWN: 'CHANGE_DROPDOWN',
    CHANGE_FILTER: 'CHANGE_FILTER',
    TOGGLE_PARENTS: 'TOGGLE_PARENTS',
    FETCH_PEOPLE_REQUEST: 'FETCH_PEOPLE_REQUEST',
    FETCH_PEOPLE_FAILURE: 'FETCH_PEOPLE_FAILURE',
    FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS'
}

export default ACTION_TYPES;
