// flow-typed signature: 8b85865b8dff01b138872ea3f4608586
// flow-typed version: <<STUB>>/babel-es6-polyfill_v^1.1.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-es6-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-es6-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-es6-polyfill/browser-polyfill' {
  declare module.exports: any;
}

declare module 'babel-es6-polyfill/browser-polyfill.min' {
  declare module.exports: any;
}

declare module 'babel-es6-polyfill/es6-shim' {
  declare module.exports: any;
}

declare module 'babel-es6-polyfill/gulpfile' {
  declare module.exports: any;
}

declare module 'babel-es6-polyfill/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-es6-polyfill/browser-polyfill.js' {
  declare module.exports: $Exports<'babel-es6-polyfill/browser-polyfill'>;
}
declare module 'babel-es6-polyfill/browser-polyfill.min.js' {
  declare module.exports: $Exports<'babel-es6-polyfill/browser-polyfill.min'>;
}
declare module 'babel-es6-polyfill/es6-shim.js' {
  declare module.exports: $Exports<'babel-es6-polyfill/es6-shim'>;
}
declare module 'babel-es6-polyfill/gulpfile.js' {
  declare module.exports: $Exports<'babel-es6-polyfill/gulpfile'>;
}
declare module 'babel-es6-polyfill/polyfill.js' {
  declare module.exports: $Exports<'babel-es6-polyfill/polyfill'>;
}
