// flow-typed signature: e1018c30e9235d605eec192f9bb5b04a
// flow-typed version: <<STUB>>/fetch-polyfill_v^0.8.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-polyfill/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-polyfill/fetch.js' {
  declare module.exports: $Exports<'fetch-polyfill/fetch'>;
}
