// flow-typed signature: 30ecdb01937a7c865925356fa4fcfe5f
// flow-typed version: <<STUB>>/gulp-jsonminify_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-jsonminify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-jsonminify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-jsonminify/index' {
  declare module.exports: $Exports<'gulp-jsonminify'>;
}
declare module 'gulp-jsonminify/index.js' {
  declare module.exports: $Exports<'gulp-jsonminify'>;
}
