// flow-typed signature: 76c84be9b94528fc0569da24f32c40a7
// flow-typed version: <<STUB>>/react-loadable_v^3.1.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loadable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loadable/flow-typed/webpack' {
  declare module.exports: any;
}

declare module 'react-loadable/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loadable/flow-typed/webpack.js' {
  declare module.exports: $Exports<'react-loadable/flow-typed/webpack'>;
}
declare module 'react-loadable/lib/index.js' {
  declare module.exports: $Exports<'react-loadable/lib/index'>;
}
